security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\Utilisateur:
            algorithm: bcrypt
    providers:
        users_in_memory: { memory: null }
        app_users:
            entity:
                class: App\Entity\Utilisateur
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_users
            form_login:
                login_path: login
                check_path: login
                default_target_path: /projets/mes-projets
                always_use_default_target_path: true
            logout:
                path: logout
    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER] # ROLE_ADMIN inclut ROLE_USER
    access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/logout, roles: PUBLIC_ACCESS }
    - { path: ^/$, roles: PUBLIC_ACCESS }
    - { path: ^/projets/mes-projets, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/projet/.*/cables, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/projets/\d+/recrutement, roles: IS_AUTHENTICATED_FULLY }
    - { path: ^/projets, roles: ROLE_ADMIN }
    - { path: ^/utilisateurs, roles: ROLE_ADMIN }
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
